CREATE DATABASE UBER ;
USE UBER ;

CREATE TABLE RIDER 
(
 RIDER_ID INT PRIMARY KEY  ,
 RIDER_NAME VARCHAR (35) ,
 PICKUP_LOCATION VARCHAR(30),
 RIDE_FARE INT ,
 AVAILABILITY VARCHAR(20) ,
 OTP INT
);

CREATE TABLE CUSTOMER 
(CUSTOMER_LOGIN INT primary KEY  ,
 CUSTOMER_NAME VARCHAR(20) ,
 DROP_LOCATION VARCHAR (25),
 CUSTOMER_ID INT  ,
 FOREIGN KEY CUSTOMER( CUSTOMER_ID) REFERENCES RIDER(RIDER_ID)
);

SELECT * FROM RIDER 
INNER JOIN CUSTOMER
ON RIDER .RIDER_ID =CUSTOMER.CUSTOMER_ID ;

SELECT * FROM RIDER
LEFT JOIN CUSTOMER
ON RIDER .RIDER_ID =CUSTOMER.CUSTOMER_ID ;

SELECT * FROM RIDER
RIGHT JOIN CUSTOMER
ON RIDER .RIDER_ID =CUSTOMER.CUSTOMER_ID ;

SELECT * FROM RIDER
CROSS JOIN CUSTOMER ;


