CREATE DATABASE UBER ;
USE UBER ;

CREATE TABLE RIDER 
(
 RIDER_ID INT PRIMARY KEY  ,
 RIDER_NAME VARCHAR (35) ,
 PICKUP_LOCATION VARCHAR(30),
 RIDE_FARE INT ,
 AVAILABILITY VARCHAR(20) ,
 RIDER_OTP INT ,
 PICKUP_DATE varchar(20)
);

ALTER TABLE RIDER
DROP COLUMN  PICKUP_DATE ;

ALTER TABLE RIDER ADD COLUMN PICKUP_DATE DATETIME ;
ALTER TABLE RIDER ADD COLUMN RIDER_NUMBER INT ;
ALTER TABLE CUSTOMER ADD COLUMN CUSTOMER_NUMBER INT ;


CREATE TABLE CUSTOMER 
(
CUSTOMER_ID INT PRIMARY KEY ,
CUSTOMER_NAME varchar (20),
DROP_LOCATION VARCHAR (30),
DURATION INT ,
foreign key CUSTOMER(CUSTOMER_ID) references RIDER(RIDER_ID)
) ;

SELECT * FROM RIDER 
INNER JOIN CUSTOMER
ON RIDER .RIDER_ID =CUSTOMER.CUSTOMER_ID ;

SELECT * FROM RIDER
LEFT JOIN CUSTOMER
ON RIDER .RIDER_ID =CUSTOMER.CUSTOMER_ID ;

SELECT * FROM RIDER
RIGHT JOIN CUSTOMER
ON RIDER .RIDER_ID =CUSTOMER.CUSTOMER_ID ;

SELECT * FROM RIDER
CROSS JOIN CUSTOMER ;
